---
# tasks file for roles/nginx
- name: Create NGINX container
  docker_container:
    name: "{{ container_name }}"
    image: tanyaharutyunyan/nginx:{{ image_tag }}
    recreate: yes
    ports:
      - "{{ container_port }}:80"
    restart: yes
    restart_policy: "{{ restart_policy }}"