---
# vars file for roles/ec2
security_group_name: nginx
security_group_description: Security group for NGINX
security_group_port: 8080
ec2_instance_name: nginx
key_name: devops
instance_type: t3.micro
region: eu-north-1
image_id: ami-0914547665e6a707c
ansible_user: ubuntu
