name: NGINX
env:
  IMAGE_NAME: tanyaharutyunyan/nginx
  IMAGE_TAG: ${{ github.run_number }}
  TARGET_BRANCH: master

on:
  push:
    branches: [ ${{ env.TARGET_BRANCH }} ]
  pull_request:
    branches: [ ${{ env.TARGET_BRANCH }} ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker NGINX image
        run: docker build . --file nginx/Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker NGINX image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy:

    runs-on: ubuntu-latest

    needs: [ build ]

    steps:
      - uses: actions/checkout@v3

      - name: Run EC2
        run: |
          pip install boto boto3 ansible
          ansible-galaxy collection install amazon.aws
          ansible-playbook -e aws_access_key=${{ secrets.AWS_ACCESS_KEY }} -e aws_secret_key=${{ secrets.AWS_SECRET_KEY }} ansible/ec2.yml

      - name: Read Public IP
        id: public_ip
        run: echo "::set-output name=PUBLIC_IP::$(cat ansible/files/ec2_public_ip.txt)"

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add keyscan
        run: |
          ssh-keyscan ${{ steps.public_ip.outputs.public_ip }} >> ~/.ssh/known_hosts

      - name: Run NGINX
        run: |
          ansible-playbook -i ansible/inventory.ini -e image_name=${{ env.IMAGE_NAME }} -e image_tag=${{ env.IMAGE_TAG }} ansible/nginx.yml
